# coding: utf-8
#
# modify header contents for amp html
#
# Copyright (c) 2018 Youhei SASAKI <uwabami@gfd-dennou.org>
#
# You can redistribute it and/or modify it under GPL.
#
$debug = false
require 'rmagick'
require 'fileutils'

@display_mode = %w(latest day month nyear categoryview preview)

add_header_proc do
	h = %Q|\t<!-- amp toolkit info: current mode is #{@mode} -->|
end

def doctype
	%Q[<!doctype html>]
end

# 良い位置にあるので, amp preload に利用することに.
unless respond_to?(:author_mail_tag_00_amp_toolkit)
  alias :author_mail_tag_00_amp_toolkit :author_mail_tag
end
def author_mail_tag
	r = ''
	if @conf.author_name and not(@conf.author_name.empty?) then
		r += %Q[<!-- remove link rev email: obsolete HTML5 -->]
	end
	if @display_mode.include?(@mode) then
		r += %Q|<!-- amp preload -->\n| if $debug
		r += %Q|\n\t<link rel="preload" as="script" href="https://cdn.ampproject.org/v0.js">|
		r += %Q|<!-- /amp preload -->| if $debug
	end
	r
end

# ogp の下に description_tag が入る.
# 指定が無いと空行なのでデバッグ目的でコメントを挿入
unless respond_to?(:description_tag_00_amp_toolkit)
  alias :description_tag_00_amp_toolkit :description_tag
end
def description_tag
	r = ''
	r += %Q|<!-- description tag -->\n\t| if $debug
	if @conf.description and not(@conf.description.empty?) then
		r += %Q[<meta name="description" content="#{h @conf.description}">]
	end
	r
end

# ----------------------------------------------------------------
# OGP画像生成メソッド (白背景・青帯・丸アイコン)
# ----------------------------------------------------------------
def generate_og_image_card(title, date_str)
	filename = "ogp_#{date_str}.png"
	file_path = File.join(@conf['amp_ogp_dir'], filename)
	public_url = "#{@conf['amp_ogp_url']}/#{filename}"
	# キャッシュがあればURLを返して終了
	# return public_url if File.exist?(file_path)
	# --- 描画開始 ---
	width, height = 1200, 630
	header_height = 25
	footer_height = 120
	image = Magick::Image.new(width, height)
	image.background_color = @conf['amp_ogp_bg_color']
	image.erase!
	# 背景色
	draw = Magick::Draw.new
	draw.fill = @conf['amp_ogp_theme_color']
	# header
	draw.rectangle(0, 0, width, header_height)
	# footer
	draw.rectangle(0, height - footer_height, width, height)
	draw.draw(image)
	# フッタ
	footer_text = "#{@conf.html_title} / #{date_str} ".dup.force_encoding('UTF-8')
	draw.annotate(image, 0, 0, 40, 60, footer_text) do |d|
		d.font = @conf['amp_ogp_font_path']
		d.pointsize = 48
		d.fill = 'white'
		d.gravity = Magick::SouthWestGravity
		d.font_weight = Magick::BoldWeight
	end
	# フッタ下段
	powerdby_text = "Generated by tDiary #{h= TDIARY_VERSION} , Powered by Ruby #{h= RUBY_VERSION }".dup.force_encoding('UTF-8')
	draw.annotate(image, 0, 0, 40, 18, powerdby_text) do |d|
		d.font = @conf['amp_ogp_font_path']
		d.pointsize = 24
		d.fill = 'white'
		d.gravity = Magick::SouthWestGravity
		d.font_weight = Magick::BoldWeight
	end
	# ----------------------------------------------------------------------------
	# タイトルの書き出し
	# ----------------------------------------------------------------------------
	# 左右に 100px ずつの余白を持たせた 1000px 幅の「テキスト箱」を作成
	title_text = title.to_s.dup.force_encoding('UTF-8')
	title_text.sub!(/(?<=[^ -~])(?=[a-zA-Z0-9@#(\[{])|(?<=[a-zA-Z0-9@#)\]}])(?=[^ -~])/,' ')
	title_layer = Magick::Image.read("caption:#{title_text}") { |opt|
		opt.size = "1000x300"          # タイトルエリアのサイズ
		opt.font = @conf['amp_ogp_font_path']
		opt.fill = @conf['amp_ogp_fg_color']
		opt.background_color = "none"  # 背景透明
		opt.gravity = Magick::CenterGravity
	}.first
	image.composite!(title_layer, Magick::NorthGravity, 0, 140, Magick::OverCompositeOp)
	title_layer.destroy!
	# -------------------------------------------------------------------------
	# アイコン画像の丸切り抜きとフッタ右下への合成
	# -------------------------------------------------------------------------
	if File.exist?(@conf['amp_ogp_icon_path'])
		begin
			icon_size = 80
			icon_src = Magick::Image.read(@conf['amp_ogp_icon_path']).first
			icon_src.resize_to_fill!(icon_size, icon_size)
			# 型抜き土台
			icon_base = Magick::Image.new(icon_size, icon_size)
			icon_base.background_color = 'none' # 背景は透明
			icon_base.erase!                    # 確実に透明で初期化
			# 型抜き
			drawer = Magick::Draw.new
			drawer.stroke('none')
			drawer.fill('white') # 色は何でも良いが、不透明(alpha=1.0)であることが必須
			drawer.circle(icon_size/2, icon_size/2, icon_size/2, 0)
			drawer.draw(icon_base)
			# 型にアイコン画像を流し込む (SrcIn)
			icon_base.composite!(icon_src, Magick::CenterGravity, Magick::SrcInCompositeOp)
			# 本体に合成
			image.composite!(icon_base, Magick::SouthEastGravity, 40, 10, Magick::OverCompositeOp)
			# 解放
			icon_src.destroy!
			icon_base.destroy!
		rescue => e
			warn "OGP Icon Error: #{e.message}"
		end
	end
	image.write(file_path)
	image.destroy!
	return public_url
end

def ogp_tag
	h = ''
	h += %Q|<!-- ogp tag#{@display_mode.include?(@mode) ? "": ": empty for #{@mode}"} -->\n\t| if $debug
	if @display_mode.include?(@mode) then
		h += %Q|<meta property="og:type" content="article">|
		ogp = {}
		top_image = (@conf.banner.nil? || @conf.banner == '') ? File.join(@conf.base_url, "#{theme_url}/ogimage.png") : @conf.banner
		# options
		ogp['og:site_name'] = @conf.html_title
		ogp['og:description'] = short_desc.gsub(/&#8230;/,'')
		case @mode
		when 'day', 'latest'
			date_key = @date.strftime('%Y%m%d')
			diary = @diaries[date_key]
			if diary.nil? && !@diaries.empty?
				date_key = @diaries.keys.sort.last
				diary = @diaries[date_key]
			end
			subtitles = []
			if diary
				diary.each_section do |section|
					if section.subtitle && !section.subtitle.empty?
						clean_subtitle = section.subtitle.gsub(/<[^>]+>/, '')
						clean_subtitle.sub!(/^\s*(\[[^\]]+\])+\s*/, '')
						# # for org-style
						clean_subtitle.sub!(/^\s*\*+\s*/, '')
						clean_subtitle.sub!(/\s*(:[^:]+)+:\s*$/, '')
						clean_subtitle.strip!
						subtitles << clean_subtitle unless clean_subtitle.empty?
					end
				end
			end
			if subtitles.empty?
				ogp['og:title'] = title_tag.gsub(/<[^>]*>/, "")
			else
				ogp['og:title'] = subtitles.join(' / ')
			end
			ogp['og:url'] = URI.join(@conf.base_url, anchor(date_key))
			begin
		 		ogp['og:image'] = generate_og_image_card(ogp['og:title'], date_key)
			rescue => e
				ogp['og:image'] = top_image
			end
		when 'nyear'
			ogp['og:title'] = title_tag.gsub(/<[^>]*>/, "")
			ogp['og:url'] = URI.join(@conf.base_url, anchor(@cgi.params['date'][0].to_s))
			image = (@conf.banner.nil? || @conf.banner == '') ? File.join(@conf.base_url, "#{theme_url}/ogimage.png") : @conf.banner
			ogp['og:image'] = top_image
		when 'month'
			ogp['og:title'] = title_tag.gsub(/<[^>]*>/, "")
			ogp['og:url'] = URI.join(@conf.base_url, anchor(@date.strftime('%Y%m')))
			image = (@conf.banner.nil? || @conf.banner == '') ? File.join(@conf.base_url, "#{theme_url}/ogimage.png") : @conf.banner
			ogp['og:image'] = top_image
		else
			#		ogp['og:type'] = 'website'
			#		ogp['og:url'] = uri
		end
		if @conf['twitter.user']
			ogp['twitter:card'] = 'summary_large_image'
			ogp['twitter:site'] = "@#{@conf['twitter.user']}"
			ogp['twitter:url' ] = ogp['og:url']
			ogp['twitter:title'] = ogp['og:title']
			ogp['twitter:description'] = ogp['og:description']
			ogp['twitter:image'] = ogp['og:image']
		end
		if @conf['facebook.appid']
			ogp['fb:appid'] = "#{conf['facebook.appid']}"
		end
		ogp.map { |k, v|
			h << %Q|\n	<meta property="#{k}" content="#{h(v)}">|
		}
		h += <<-LD_JSON_HEAD
\n\t<script type="application/ld+json">
	{
		"@context": "http://schema.org",
		"@type": "BlogPosting",
			"mainEntityOfPage":{
				"@type":"WebPage",
				"@id":"#{@conf.base_url}"
			},
			"headline": "#{ogp['og:title']}",
			"image": {
				"@type": "ImageObject",
				"url": "#{@conf.banner}",
				"height": 480,
				"width": 640
			},
LD_JSON_HEAD
		case @mode
		when 'day'
			h <<%Q|			"datePublished": "#{@diaries[@date.strftime('%Y%m%d')].date.iso8601}",\n|
			h <<%Q|			"dateModified": "#{@diaries[@date.strftime('%Y%m%d')].last_modified.iso8601}",\n|
		when 'latest'
			h <<%Q|			"datePublished": "#{@diaries[@date.strftime('%Y%m%d')].date.iso8601}",\n|
			h <<%Q|			"dateModified": "#{@diaries[@date.strftime('%Y%m%d')].last_modified.iso8601}",\n|
		when 'month'
			h <<%Q|			"datePublished": "#{@diaries.sort[0][1].date.iso8601}",\n|
			h <<%Q|			"dateModified": "#{@diaries.sort[-1][1].date.iso8601}",\n|
		when 'nyear'
			h <<%Q|			"datePublished": "#{@diaries.sort[0][1].date.iso8601}",\n|
			h <<%Q|			"dateModified": "#{@diaries.sort[-1][1].date.iso8601}",\n|
		end
		h += <<-LD_JSON_BOTTOM.chomp
			"author": {
				"@type": "Person",
				"name": "#{@conf.author_name}",
				"image": "#{@conf['amp_ogp_author_image_url']}"
			},
			"publisher": {
				"@type": "Organization",
				"name": "#{@conf.author_name}",
				"logo": {
					"@type": "ImageObject",
					"url": "#{ogp['og:image']}",
					"height": 240,
					"width": 320
				}
			},
		"description": "#{ogp['og:description']}"
	}
	</script>
LD_JSON_BOTTOM
	end
	h
end

unless respond_to?(:css_tag_00_amp_toolkit)
  alias :css_tag_00_amp_toolkit :css_tag
end
def css_tag
	%Q|<!-- css tag: (re)moved.-->|
end

unless respond_to?(:jquery_tag_00_amp_toolkit)
  alias :jquery_tag_00_amp_toolkit :jquery_tag
end
def jquery_tag
	%Q|<!-- jquery tag: (re)moved to footer -->|
end

unless respond_to?(:script_tag_00_amp_toolkit)
  alias :script_tag_00_amp_toolkit :script_tag
end
def script_tag
	%Q|<!-- script tag: (re)moved to footer -->|
end

# <title></title> の下に robot_control が入る.
# これを amp-boilerplate の挿入に利用する
unless respond_to?(:robot_control_00_amp_toolkit)
  alias :robot_control_00_amp_toolkit :robot_control
end
def robot_control
	h = ''
	h += %Q|<!-- robot contool tag -->\n\t| if $debug
	if @display_mode.include?(@mode) then
		h += %Q|<script async src=\"https://cdn.ampproject.org/v0.js\"></script>\n|
		h += %Q|\t<style amp-custom>#{amp_theme_css.chomp}#{amp_conf_css.chomp}</style>\n|
		h += %Q|\t<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>\n|
	else
		h += %Q|\t<style>#{amp_theme_css.chomp}#{amp_conf_css.chomp}</style>|
		h += %Q|\t|
		h += robot_control_00_amp_toolkit
	end
	case @mode
	when 'latest'
		h += %Q|\t<link rel="canonical" href="#{URI.join(@conf.base_url, anchor(@date.strftime('%Y%m%d')))}">|
	when 'day'
		h += %Q|\t<link rel="canonical" href="#{URI.join(@conf.base_url, anchor(@date.strftime('%Y%m%d')))}">|
	when 'month'
		h += %Q|\t<link rel="canonical" href="#{URI.join(@conf.base_url, anchor(@date.strftime('%Y%m')))}">|
	when 'nyear'
		h += %Q|\t<link rel="canonical" href="#{URI.join(@conf.base_url, anchor(@cgi.params['date'][0].to_s))}">|
	else
		#
	end
	h
end

def amp_conf_css   # <-- from amp.rb
	_, location, theme = @conf.theme.match(%r|(\w+)/(\w+)|).to_a
	case location
	when 'online'
		require 'uri'
		require 'open-uri'
		uri = URI.parse(theme_url_online(theme))
		uri.scheme ||= 'https'
		URI.parse(uri.to_s).read
	when 'local'
		theme_path = theme_paths_local.map {|path|
			File.join(File.dirname(path), "#{theme}/conf.css")
		}.find {|path|
			File.exist?(path)
		}
		theme_path ? File.read(theme_path) : ''
	end
end

def amp_theme_css  # <-- from amp.rb
	_, location, theme = @conf.theme.match(%r|(\w+)/(\w+)|).to_a
	case location
	when 'online'
		require 'uri'
		require 'open-uri'
		uri = URI.parse(theme_url_online(theme))
		uri.scheme ||= 'https'
		URI.parse(uri.to_s).read
	when 'local'
		theme_path = theme_paths_local.map {|path|
			File.join(File.dirname(path), "#{theme}/#{theme}.css")
		}.find {|path|
			File.exist?(path)
		}
		theme_path ? File.read(theme_path) : ''
	end
end

add_footer_proc do
	footer = ""
	unless @display_mode.include?(@mode) then
		footer += <<-FOOTER
<!-- original: jqeury_tag -->
#{jquery_tag_00_amp_toolkit.chomp}
<!-- original: script_tag -->
#{script_tag_00_amp_toolkit.chomp}
FOOTER
	end
end

add_conf_proc('00_amp_toolkit', 'amp toolkit', 'basic') do
	if @mode == 'saveconf' then
		@conf['amp_ogp_dir'] = @cgi.params['amp_ogp_dir'][0]
		@conf['amp_ogp_url'] = @cgi.params['amp_ogp_url'][0]
		@conf['amp_ogp_theme_color'] = @cgi.params['amp_ogp_theme_color'][0]
		@conf['amp_ogp_bg_color'] = @cgi.params['amp_ogp_bg_color'][0]
		@conf['amp_ogp_fg_color'] = @cgi.params['amp_ogp_fg_color'][0]
		@conf['amp_ogp_font_path'] = @cgi.params['amp_ogp_font_path'][0]
		@conf['amp_ogp_icon_path'] = @cgi.params['amp_ogp_icon_path'][0]
		@conf['amp_ogp_author_image_url'] = @cgi.params['amp_ogp_author_image_url'][0]
	end
	r = <<-HTML
<h4>生成する OGP 画像の保存先</h4>
<p>CGIが読み書きできる場所,
公開できる場所である必要があります<br>
<input name="amp_ogp_dir"></p>
<!-- %%%%% -->
<h4>生成する OGP 画像の URL</h4>
<p>
OGP の JSON で指定します.
<pre>以下で指定したURL + /ogp_日付.png</pre>
でアクセスできる必要があります<br>
<p><input name="amp_ogp_url"></p>
<!-- %%%%% -->
<h4>OGP 画像のヘッダ・フッタの色</h4>
<p><input name="amp_ogp_theme_color"></p>
<!-- %%%%% -->
<h4>OGP 画像の背景色</h4>
<p><input name="amp_ogp_bg_color"></p>
<!-- %%%%% -->
<h4>OGP 画像の前景色</h4>
<p><input name="amp_ogp_fg_color"></p>
<!-- %%%%% -->
<h4>OGP 画像のフォント</h4>
<p>システムのフォントファイルの場所を指定して下さい<br>
<input name="amp_ogp_font_path"></p>
<!-- %%%%% -->
<h4>OGP 画像のアイコン</h4>
<p>OGPカードに掲載するアイコン画像の場所<br>
<input name="amp_ogp_icon_path"></p>
<!-- %%%%% -->
<h4>OGP 画像の著者画像</h4>
<p>OGPカードに掲載する著者画像の公開URL<br>
<input name="amp_ogp_author_image_url"></p>
HTML
	r
end

# Local Variables:
# mode: ruby
# indent-tabs-mode: t
# tab-width: 3
# ruby-indent-level: 3
# End:
# vim: ts=3
